In [28]:
import tensorflow as tf
from sklearn.datasets import load_iris
from keras.utils import to_categorical

In [29]:
tf.enable_eager_execution()

In [30]:
data = load_iris()

In [31]:
X,y = data.data,data.target

In [32]:
y = to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [33]:
W = tf.truncated_normal((4,7))

In [34]:
b = tf.zeros([7])

In [35]:
W,b

(<tf.Tensor: id=133, shape=(4, 7), dtype=float32, numpy=
 array([[-0.667906  , -0.6281231 ,  0.2238849 ,  1.222088  ,  0.13592592,
          0.22120658, -0.13685845],
        [-0.25983402, -0.93598366, -0.8185558 , -0.09527095,  1.2987562 ,
         -0.98902047, -0.11171625],
        [ 1.4806308 , -1.3132731 ,  0.20190196,  0.83632475, -0.14488514,
          0.15798415,  0.61679965],
        [ 0.87302256, -0.44896412, -0.36449432,  0.0902561 , -0.4382528 ,
         -1.4809823 ,  0.03306497]], dtype=float32)>,
 <tf.Tensor: id=135, shape=(7,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

(<tf.Tensor: id=133, shape=(4, 7), dtype=float32, numpy=
 array([[-0.667906  , -0.6281231 ,  0.2238849 ,  1.222088  ,  0.13592592,
          0.22120658, -0.13685845],
        [-0.25983402, -0.93598366, -0.8185558 , -0.09527095,  1.2987562 ,
         -0.98902047, -0.11171625],
        [ 1.4806308 , -1.3132731 ,  0.20190196,  0.83632475, -0.14488514,
          0.15798415,  0.61679965],
        [ 0.87302256, -0.44896412, -0.36449432,  0.0902561 , -0.4382528 ,
         -1.4809823 ,  0.03306497]], dtype=float32)>,
 <tf.Tensor: id=135, shape=(7,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [36]:
input1 = tf.constant(X, dtype=tf.float32)
hidden_layer = tf.nn.relu(tf.matmul(input1,W) + b)

In [37]:
W_2 = tf.truncated_normal((7,5))
b_2 = tf.zeros([5])
hidden_layer_2 = tf.nn.relu(tf.matmul(hidden_layer,W_2) + b_2)

In [38]:
W_3 = tf.truncated_normal((5,3))
b_3 = tf.zeros([3])
hidden_layer_3 = tf.nn.relu(tf.matmul(hidden_layer_2,W_3) + b_3)


In [39]:
output_layer = tf.nn.softmax_cross_entropy_with_logits(logits = hidden_layer_3, labels = y)

In [40]:
tf.reduce_mean(output_layer)

<tf.Tensor: id=190, shape=(), dtype=float32, numpy=4.592377>

<tf.Tensor: id=190, shape=(), dtype=float32, numpy=4.592377>