In [1]:
import tensorflow as tf
from sklearn.datasets import load_iris
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
tf.enable_eager_execution()

In [3]:
data = load_iris()

In [4]:
X,y = data.data,data.target

In [5]:
y = to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [6]:
W = tf.truncated_normal((4,7))

In [7]:
b = tf.zeros([7])

In [8]:
W,b

(<tf.Tensor: id=6, shape=(4, 7), dtype=float32, numpy=
 array([[ 1.410533  , -1.0128366 , -0.13202079,  1.0554534 , -1.481086  ,
         -0.8094466 , -0.51630366],
        [ 1.1001304 , -0.97575283, -0.39526254,  0.8231988 ,  1.0461856 ,
         -1.1503353 , -0.15167077],
        [ 1.2274241 ,  0.31127292, -0.43887   ,  1.447597  , -1.4204013 ,
          0.7465664 , -1.6880358 ],
        [ 0.0068153 ,  0.00602025, -0.6297908 , -0.5949632 ,  0.19797665,
          0.45517713,  0.07572863]], dtype=float32)>,
 <tf.Tensor: id=9, shape=(7,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [9]:
input1 = tf.constant(X, dtype=tf.float32)
hidden_layer = tf.nn.relu(tf.matmul(input1,W) + b)

In [10]:
W_2 = tf.truncated_normal((7,5))
b_2 = tf.zeros([5])
hidden_layer_2 = tf.nn.relu(tf.matmul(hidden_layer,W_2) + b_2)

In [11]:
W_3 = tf.truncated_normal((5,3))
b_3 = tf.zeros([3])
hidden_layer_3 = tf.nn.relu(tf.matmul(hidden_layer_2,W_3) + b_3)


In [16]:
y.shape

(150, 3)

In [12]:
output_layer = tf.nn.softmax_cross_entropy_with_logits(logits = hidden_layer_3, labels = y)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [14]:
output_layer

<tf.Tensor: id=64, shape=(150,), dtype=float32, numpy=
array([37.62042 , 35.121025, 34.62691 , 34.48815 , 37.52719 , 41.278458,
       35.242973, 37.174007, 32.672356, 35.687878, 39.859867, 36.634365,
       34.62616 , 31.584948, 41.622757, 43.586193, 40.047836, 37.691635,
       42.147762, 38.990555, 39.48392 , 38.731354, 34.60197 , 38.096203,
       37.557335, 36.159985, 37.6241  , 38.351727, 37.713646, 35.549877,
       35.643105, 39.011044, 40.263027, 41.627956, 35.759098, 35.5902  ,
       39.007366, 37.032326, 32.695126, 37.597656, 36.96034 , 30.877054,
       33.355965, 38.096954, 40.2924  , 34.768593, 39.226994, 34.510914,
       39.436214, 36.53593 , 55.685757, 52.59977 , 55.61821 , 44.132427,
       52.00939 , 48.1701  , 53.193066, 39.55371 , 52.621017, 43.946724,
       39.27099 , 48.897717, 45.706604, 50.88165 , 45.307972, 53.161415,
       48.549732, 46.819054, 48.44827 , 44.766823, 51.618137, 48.32642 ,
       51.093803, 50.408806, 50.85076 , 52.40734 , 53.82443 , 54.8905

In [17]:
tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=hidden_layer_3, labels=y))

<tf.Tensor: id=95, shape=(), dtype=float32, numpy=28.519577>